config/routes.rb
Issflyby::Application.routes.draw do
  resources :cards

  resources :subscriptions

  resources :spacepeople

	resources :passes
	resources :spacecrafts

	root :to => 'application#index'

  get '/auth/failure', to: 'sessions#auth_failure'
	get '/auth/:provider/callback', to: 'sessions#create'
	get '/sign_in', to: 'sessions#new', as: 'sign_in'
	get '/privacy', to: 'pages#privacy', as: 'privacy'
	get '/terms', to: 'pages#terms', as: 'terms'
	get '/sign_out', to: 'sessions#destroy', as: 'sign_out'
	get '/press', to: 'pages#press', as: 'press'
  get '/demo_card', to: 'users#demo_card', as: 'demo_card'
end

app/models/spacecraft.rb
class Spacecraft < ActiveRecord::Base
  attr_accessible :name, :lat, :long, :endpoint

  #name used by open-notify.org for spacecraft in API
    attr_accessible :apiname

  validates_presence_of :name
  has_many :passes, dependent: :destroy
  has_many :spacepeople, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  #def self.locate_iss
  #  location = HTTParty.get('http://api.open-notify.org/iss-now.json')
  #end
  #
  #def self.update_iss_location
  #	location = HTTParty.get('http://api.open-notify.org/iss-now.json')
  #  iss = Spacecraft.find_or_create_by(name: 'ISS')
  #  iss.update(lat:location['iss_position']['latitude'], long: location['iss_position']['latitude'])
  #end

  def check_spacepeople
    astros = HTTParty.get('http://api.open-notify.org/astros.json')

    if astros
      #remove previous spacepeople
        self.spacepeople.destroy_all

      #create spacepeople
        astros['people'].each do |astro|
          if astro['craft'] == self.apiname
            Spaceperson.create(spacecraft_id:self.id,name:astro['name'])
          end
        end

      #update crew integer
        self.crew = astros['number'].to_i
        self.save
    end
  end

  def fire_laser(lat,lon,intensity)
    #TODO fire space laser at any place on Earth
  end
end

app/controllers/spacecrafts_controller.rb
class SpacecraftsController < ApplicationController
  before_action :set_spacecraft, only: [:show, :edit, :update, :destroy]
  before_action :can_has_admin?, except: :show

  # GET /spacecrafts
  # GET /spacecrafts.json
  def index
    @spacecrafts = Spacecraft.all
  end

  # GET /spacecrafts/1
  # GET /spacecrafts/1.json
  def show
  end

  # GET /spacecrafts/new
  def new
    @spacecraft = Spacecraft.new
  end

  # GET /spacecrafts/1/edit
  def edit
  end

  # POST /spacecrafts
  # POST /spacecrafts.json
  def create
    @spacecraft = Spacecraft.new(spacecraft_params)

    respond_to do |format|
      if @spacecraft.save
        format.html { redirect_to @spacecraft, notice: 'Spacecraft was successfully created.' }
        format.json { render action: 'show', status: :created, location: @spacecraft }
      else
        format.html { render action: 'new' }
        format.json { render json: @spacecraft.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spacecrafts/1
  # PATCH/PUT /spacecrafts/1.json
  def update
    respond_to do |format|
      if @spacecraft.update(spacecraft_params)
        format.html { redirect_to @spacecraft, notice: 'Spacecraft was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @spacecraft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spacecrafts/1
  # DELETE /spacecrafts/1.json
  def destroy
    @spacecraft.destroy
    respond_to do |format|
      format.html { redirect_to spacecrafts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spacecraft
      @spacecraft = Spacecraft.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spacecraft_params
      params.require(:spacecraft).permit(:name, :crew, :lat, :long)
    end
end

app/helpers/spacecrafts_helper.rb
module SpacecraftsHelper
end

app/views/spacecrafts/_form.html.erb
<%= form_for(@spacecraft) do |f| %>
  <% if @spacecraft.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spacecraft.errors.count, "error") %> prohibited this spacecraft from being saved:</h2>

      <ul>
      <% @spacecraft.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :crew %><br>
    <%= f.number_field :crew %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br>
    <%= f.text_field :long %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spacecrafts/edit.html.erb
<h1>Editing spacecraft</h1>

<%= render 'form' %>

<%= link_to 'Show', @spacecraft %> |
<%= link_to 'Back', spacecrafts_path %>

app/views/spacecrafts/index.html.erb
<h1>Listing spacecrafts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Crew</th>
      <th>Lat</th>
      <th>Long</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @spacecrafts.each do |spacecraft| %>
      <tr>
        <td><%= spacecraft.name %></td>
        <td><%= spacecraft.crew %></td>
        <td><%= spacecraft.lat %></td>
        <td><%= spacecraft.long %></td>
        <td><%= link_to 'Show', spacecraft %></td>
        <td><%= link_to 'Edit', edit_spacecraft_path(spacecraft) %></td>
        <td><%= link_to 'Destroy', spacecraft, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spacecraft', new_spacecraft_path %>

app/views/spacecrafts/new.html.erb
<h1>New spacecraft</h1>

<%= render 'form' %>

<%= link_to 'Back', spacecrafts_path %>

app/views/spacecrafts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @spacecraft.name %>
</p>

<p>
  <strong>Crew:</strong>
  <%= @spacecraft.crew %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @spacecraft.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @spacecraft.long %>
</p>

<%= link_to 'Edit', edit_spacecraft_path(@spacecraft) %> |
<%= link_to 'Back', spacecrafts_path %>