config/routes.rb
Issflyby::Application.routes.draw do
  resources :cards

  resources :subscriptions

  resources :spacepeople

	resources :passes
	resources :spacecrafts

	root :to => 'application#index'

  get '/auth/failure', to: 'sessions#auth_failure'
	get '/auth/:provider/callback', to: 'sessions#create'
	get '/sign_in', to: 'sessions#new', as: 'sign_in'
	get '/privacy', to: 'pages#privacy', as: 'privacy'
	get '/terms', to: 'pages#terms', as: 'terms'
	get '/sign_out', to: 'sessions#destroy', as: 'sign_out'
	get '/press', to: 'pages#press', as: 'press'
  get '/demo_card', to: 'users#demo_card', as: 'demo_card'
end

app/controllers/passes_controller.rb
class PassesController < ApplicationController
  before_action :set_pass, only: [:show, :edit, :update, :destroy]
  before_action :can_has_admin?

  # GET /passes
  # GET /passes.json
  def index
    @passes = Pass.all
  end

  # GET /passes/1
  # GET /passes/1.json
  def show
  end

  # GET /passes/new
  def new
    @pass = Pass.new
  end

  # GET /passes/1/edit
  def edit
  end

  # POST /passes
  # POST /passes.json
  def create
    @pass = Pass.new(pass_params)

    respond_to do |format|
      if @pass.save
        format.html { redirect_to @pass, notice: 'Pass was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pass }
      else
        format.html { render action: 'new' }
        format.json { render json: @pass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passes/1
  # PATCH/PUT /passes/1.json
  def update
    respond_to do |format|
      if @pass.update(pass_params)
        format.html { redirect_to @pass, notice: 'Pass was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passes/1
  # DELETE /passes/1.json
  def destroy
    @pass.destroy
    respond_to do |format|
      format.html { redirect_to passes_url }
      format.json { head :no_content }
    end
  end
  def duration_in_minutes
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pass
      @pass = Pass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pass_params
      params.require(:pass).permit(:risetime, :duration, :user_id, :duration_in_minutes)
    end
end

app/helpers/passes_helper.rb
module PassesHelper
end

app/views/passes/_form.html.erb
<%= form_for(@pass) do |f| %>
  <% if @pass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pass.errors.count, "error") %> prohibited this pass from being saved:</h2>

      <ul>
      <% @pass.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :risetime %><br>
    <%= f.datetime_select :risetime %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/passes/edit.html.erb
<h1>Editing pass</h1>

<%= render 'form' %>

<%= link_to 'Show', @pass %> |
<%= link_to 'Back', passes_path %>

app/views/passes/index.html.erb
<h1>Listing passes</h1>

<table>
  <thead>
    <tr>
      <th>Risetime</th>
      <th>Duration</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @passes.each do |pass| %>
      <tr>
        <td><%= pass.risetime %></td>
        <td><%= pass.duration %></td>
        <td><%= pass.user_id %></td>
        <td><%= link_to 'Show', pass %></td>
        <td><%= link_to 'Edit', edit_pass_path(pass) %></td>
        <td><%= link_to 'Destroy', pass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pass', new_pass_path %>

app/views/passes/new.html.erb
<h1>New pass</h1>

<%= render 'form' %>

<%= link_to 'Back', passes_path %>

app/views/passes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Risetime:</strong>
  <%= @pass.risetime %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @pass.duration %>
</p>

<p>
  <strong>User:</strong>
  <%= @pass.user_id %>
</p>

<%= link_to 'Edit', edit_pass_path(@pass) %> |
<%= link_to 'Back', passes_path %>